name = "AlgebraicMultigrid"
uuid = "2169fc97-5a83-5252-b627-83903c6c433c"
version = "0.4.1"

[deps]
CompatHelper = "aa819f21-2bde-4658-8897-bab36330d9b7"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
CompatHelper = "1.3.0, 2.1, 3"
IterativeSolvers = "0.9"
julia = "1.4.0"

[extras]
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["FileIO", "JLD2", "Random"]
